### ISSUE TITLE
Hike & Bike Map and OSMPublicTransport map layers don't work anymore

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#25]
Is this only an issue on my device or is this a general problem?

**Comment by francoisfds** [comment]
Hello Altnoss. I use Mapnik so I didn't notice but it's not happening only on your device. Hike&Bike tile's server is not maintained anymore since february 2022 :
> 4. The hikebike map that we were hosting will no longer be available (no known community alternative)

Source : https://phabricator.wikimedia.org/T187601#7642399

However for OSMPublicTransport, it seems to be online (this website is useful : https://mc.bbbike.org/mc/?num=2&mt0=mapnik&mt1=public_transport). On my device there is no blank tiles, there is just not any tile... It needs to be investiguate.

**Comment by opk12** [comment]
Hello. Thank you for this great app. The OSM wiki article [`Tile servers`](https://wiki.openstreetmap.org/wiki/Tile_servers) has a list, where you might find a replacement.

The app's `OSMPublicTransport` contacts `openptmap.org`, which just hangs the connection (by the way, HTTP is privacy-unfriendly).

Instead, your bbbike link loads Öpnvkarte, `tile.memomaps.de`. This layer is [featured](https://www.openstreetmap.org/#map=5/43.485/36.211&layers=O) on the OSM website, so I assume it is going to be supported well (click the `Layers` button at the right).

WMF is a no-go since 2021. [By policy](https://wikitech.wikimedia.org/wiki/Maps/External_usage), third-parties cannot use the tile servers.

**Comment by francoisfds** [comment]
Hi, thank you for your message which is hugely accurate !

You're right, the link I watched displays Öpenvkarte, which seams to provide beautiful tiles for public transport. In the OSM article that you were referring to, it is the only serious candidate interesting for biking. The bikesharing stations which are in OSM data, are well emphasized in this layer. Moreover the mainteners claim to be open on their website https://memomaps.de. I will put it as a replacement for both Hike&Bike and OSMPublicTransport :+1:

**Comment by opk12** [comment]
Cool!

To be fair, CyclOSM is also featured on the website and renders bike-related infrastructure. But I cannot manage to load the tiles at peak hours and I think the server is a bit overloaded. [Here](https://www.cyclosm.org/#map=12/52.3728/4.8936/cyclosm) and [here](https://wiki.openstreetmap.org/wiki/CyclOSM) are the details (`https://{s}.tile-cyclosm.openstreetmap.fr/[cyclosm|cyclosm-lite]/{z}/{x}/{y}.png` and [usage policy](https://operations.osmfoundation.org/policies/tiles/)).

**Comment by francoisfds** [comment]
Finaly the release 2.0.6 is alive and contains Öpnvkarte and CyclOSM map layers, both HTTPS 😉
It is true that CyclOSM is very slow, but once in cache the map is quite usefull. Thank you @opk12 for the technical details and ideas.
