### ISSUE TITLE
working with and perhaps selecting multiple areas/services

### ISSUE THREAD

**Issue by DJCrashdummy** [francoisfds/BikeSharingHub#3]
IMHO a killer feature would be to **display more than one area/service at once** (distinguished by e.g. colour)!

it happens in bigger cities that there is more than one provider or some universities have their own system on campus within the city etc. or even sometimes operating areas of a city and its suburbs overlap... for this cases showing more than one area/service at a time would be awesome.

if not, at least **adding a possibility to mark areas/services as favourites** (which are always shown on top) may ease the situation a little bit for those who have to frequently switch between them.

**Comment by francoisfds** [comment]
That would be an interesting feature indeed. For the record, could you share the name of a city which have several providers at the same time, please ? I was not aware that this could happened. 

Regards.

**Comment by DJCrashdummy** [comment]
well... there are a few different examples - although they are not completely overlapping, sometimes they are pretty hard adjoining - like *"Velib' Métropôle, Paris"* & *"Cristolib, Créteil"*, *"Metro Bike Share, Los Angeles, CA"* & *"Breeze Bike Share, Santa Monica, CA"* or *"VRN, Mannheim"* & *"VRN, Ludwigshafen"* (just divided by a river).

or they can even merge smoothly into each other like *"Nextbike, Stansstad"*, *"Nextbike, Stans"*, *"Nextbike, Oberdorf"* and *"Nextbike, Wolfenschiessen"*. which are also an example for areas/services, which names hardly match their (whole) operating area, like mentioned in #2 (especially *"Nextbike, Stans"*).

**Comment by francoisfds** [comment]
Hi, just to let you know that this is a work in progress issue. I assume the first version will do the job, but there will be several points to improve : selection GUI, zoom level for the map when the selected networks are too far away from each other, that kind of things...

Stay tuned :wink:

**Comment by Altonss** [comment]
It has arrived in the new version, thanks @francoisfds :+1:

But I find the new selection UI a little bit buggy... I don't know if it's due to my Android 5.
And also a problem is when selecting 2 networks (e.g. in Paris area) and then wanting to switch to a totally different network (e.g. Lyon), the process is a bit too complex and not as intuitive as it was before ^^ We could maybe think of a way to improve this slightly more :)
Anyway thanks a lot for your hard work!

**Comment by francoisfds** [comment]
Hello,

Great to hear some feedback. About the buggy part, what do you mean exactly, display is too slow, that kind of thing ? Is there a difference whether the internet connection is up or down ?

Concerning the network selection, I agree it’s a bit hard : « three dots », « Settings », « Network choice », finally. A shortcut could be better.

Nevertheless I think that if you are likely to be always in the same cities (for example Paris, Créteil and Lyon), the use case I had in mind is to select those three networks. You can mark stations as favorites independently, and don't need to go often in the network selection interface. For the map, if your location is active, the map focuses automatically on your position, otherwise it focuses on the first network of your list (it may be better to zoom out to catch all stations of all networks).

**Comment by Altonss** [comment]
> Great to hear some feedback. About the buggy part, what do you mean exactly, display is too slow, that kind of thing ? Is there a difference whether the internet connection is up or down ?

2 bugs:
- when opening the network selection, the first selected network "selected box" is slower to appears than for the other selected networks
- when unselecting the only network that is selected, the result is slightly buggy

**Comment by francoisfds** [comment]
For the second one it's wanted to keep at least one network. It was not possible on previous releases to remove the sole network. So if the user remove the last network, it is selected again automatically. I understand the UI seems buggy.

**Comment by Altonss** [comment]
I would need to do some screen recording but here some info:
- when unselecting a network (and especially when it's the last) the UI is sometimes stuck/really slow: the line remains "selected" and grayed out
- when you just want to change network it is very clumsy: you need to select the new network, then it automatically closes the selection, then you need to reenter the selection menu to delete the old network...I think that for most users this is probably not very intuitive.

**Comment by Altonss** [comment]
I will open 2 separate issue for the small "bugs" I noticed :)

**Comment by Altonss** [comment]
This is now fully supported so I think we could close this issue and open new ones for specific bugs or other feature requests ;)

**Comment by francoisfds** [comment]
Indeed the main feature is available since v2.0.5.
