### ISSUE TITLE
Icon not displaying well on Samsung Galaxy A40

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#6]
With the Samsung OneUI desing the icon doesn't render well. This is just a minor issue, but maybe it would not be too difficult to tweak the icon for these devices?
This is not a priority, but just a cosmetic detail that could make the app more appealing to new users :)
![image](https://user-images.githubusercontent.com/66519591/149835750-da5a0bae-1deb-42fe-9da9-7a7869ce6c34.png)

**Comment by Altonss** [comment]
I know where this issue might come from: Adaptive icons https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.
Especially for newer devices we should target this compatibility :)

**Comment by francoisfds** [comment]
Unfortunately Adaptive Icons start from SDK 26 and we are 23 for now (there is a bug left before upgrading). In the meantime, I think that just having the same icon without any border could do the job. On this Samsung it’s already a good thing that there is no grey/blank background behind the icon.

**Comment by Altonss** [comment]
> Unfortunately Adaptive Icons start from SDK 26 and we are 23 for now (there is a bug left before upgrading).

Where is the bug located/what is it about?

**Comment by francoisfds** [comment]
It occurs when the map is opened. Something is not handled well and an exception is thrown. I don't remember exactly why but you can see a log on the current release. Starting from SDK 24 it turns into a crash.

**Comment by Altonss** [comment]
Thanks for the update!
The icon is displaying a little bit pixelated in my F-Droid app, is this also happening to you?
And on my android home screen as well, I don't know if it's Android 5 messing up the icon...

**Comment by francoisfds** [comment]
I use Android 10 and icon is OK on my home screen. But I tested on an Android 5.1.1, Samsung (screenshots bellow) and it's OK too both home screen and F-Droid icon. However the banner is pixelated like it was before.

![Screenshot_homescreen](https://user-images.githubusercontent.com/15369785/160246265-7fbed38a-2e99-4871-94bd-5cb213a0b16b.png) ![Screenshot_fdroidclient](https://user-images.githubusercontent.com/15369785/160246309-328560b4-1c27-4599-acf4-d1be889648a9.png)

May be your problem is due to the fact that icons are vectorized now.

What is the behaviour for Samsung Galaxy A40 ?

**Comment by Altonss** [comment]
I don't have the Galaxy A40 right now, but I soon as I can test it I will give my feedback.
Here is my screenshot of F-Droid:
![image](https://user-images.githubusercontent.com/66519591/160246488-b9303025-65f0-4510-af4d-9a56a9ca68f8.png)

Here my screenshot on Android 5: (here compared to Catima)
![image](https://user-images.githubusercontent.com/66519591/160246531-6541d181-2721-467b-82a5-2c73e6315fef.png)

These issues might be related to my device (and my older version of F-Droid), so don't worry :)

**Comment by francoisfds** [comment]
> Thanks for the update! The icon is displaying a little bit pixelated in my F-Droid app, is this also happening to you? And on my android home screen as well, I don't know if it's Android 5 messing up the icon...

Since release 2.0.6 the icon in F-Droid must be OK, isn't it ? It was written in the docs that "the app icon is mandatory if your app doesn't include any png icon" (https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots).
So new there is a PNG icon in the fastlane directory : https://github.com/francoisfds/BikeSharingHub/blob/master/fastlane/metadata/android/en-US/images/icon.png

As for the launcher icon, we will put PNG icon back for Android version < 8.0.0 and keep going with vectorized form for recent Android.

**Comment by Altonss** [comment]
> Since release 2.0.6 the icon in F-Droid must be OK, isn't it ?

Looks good on my device :ok_hand:
