### ISSUE TITLE
Some unavailable stations aren't marked as such

### ISSUE THREAD

**Issue by Altonss** [francoisfds/BikeSharingHub#66]
For example Saint-Jacques - Val de Grâce, Vélib (Paris).

**Comment by francoisfds** [comment]
Hello @Altonss,

Thank you for noticing this !
Currently the stations are marked as closed depending of some pybikes extra field if they exist (like `status`, `open`, `installed`...) otherwise if both bikes and slots are 0 (like for velib).

After looking at some cases like "Saint-Jacques - Val de Grâce", I noticed that there are two other extra fields (inherited from GBFS) that are not yet used in BikeSharingHub : `is_renting` and `is_returning`. If one of them is 0 then the stations must be marked as closed (I assume there's no need to distinguish them).

This improvement will be out soon !

Thanks again,
François

**Comment by francoisfds** [comment]
It would be wrong because as far as I know the content of `extra` is not deterministic in pybikes. It gathers some extra info that not all networks has (`is_renting` is mandatory in GBFS but not all networks uses GBFS). See for example system "BUGA" (city of Aveiro) : `is_renting`  is not available in extra (instead there is `online`), so we could not rely on the non availability of this field.

**Comment by francoisfds** [comment]
Changes are out in version 2.1.2.
